//CALL BY VALUE & CALL BY REFERENCE
#include <stdio.h>
int main()
{
    
    return 0;
}
//PIC1
//ACTUAL PARAMETER = given by main to a function
//PARAMETERS CAN BE GLOBAL OR LOCAL
//LOCAL ONLY WORKS IN IT'S OWN FUNCTION
//FUNCTION GET FORMAL PARAMETERS THAT ARE COPY OF ACTUAL PARAMETER..EXAMPLE..SHARING INFORMATION IN EXAM
//PIC2
//CALL BY VALUE...COPY GOES TO FUNCTION..ORIGINAL REMAINS SAME..
//CALL BY REFERENCE..USE POINTER..GIVE ADDRESS..FUNCTION GET ACCESS TO ACTUAL PARAMETER..THUS CHANGE THE VALUE